on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        options: [release, pre-release]

name: Import latest packages
jobs:
  import_latest_packages:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Import latest packages
        env:
          CHANNEL: ${{ inputs.channel }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./manage-repo.sh import_latest_packages
